#!/usr/bin/env python3

import glob
import re

print("// This file was autogenerated by generate.py")
print("")
print("PCanDB := AssociativeArray();")

for fname in sorted(glob.glob('./Type-*-P-*')):
    with open(fname) as f:
        lines = [
            line.strip() for line in f
            if line.strip() and not line.strip().startswith('#')
        ]

    print()
    print(f'PCanDB["{fname.split("/")[1]}"] := [');
    for i, line in enumerate(lines, start=1):
        print(f'    "{line}"{"," if i != len(lines) else ""}')
    print('];')

